apiVersion: v1
kind: Namespace
metadata:
  name: wiki-app
  labels:
    name: wiki-app
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: wiki-app-quota
  namespace: wiki-app
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: wiki-app-limits
  namespace: wiki-app
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container